### ISSUE TITLE
README.md seems outdated/incorrect?

### ISSUE THREAD

**Issue by mchandleraz** [jillesme/node-upload#4]
The README says that running gulp will run the app, which isn't the case. Gulp does watch files as README.md claims, but doesn't run the app and also doesn't offer any live-reload capability.

I vote for changing the README to match actual functionality in the short term, and adding gulp-connect or similar to provide a server w/ livereload.

**Comment by jillesme** [comment]
The README.md file never claims any live-reload capability. It simply says that you do not have to re-run the app. If you want to implement it that's cool.

Hence https://github.com/jillesme/node-upload/blob/master/gulpfile.js#L31-L34
